In [1]:
import pandas as pd
import numpy as np
#import matplotlib as plt
#from matplotlib import pyplot
#import scipy as sp
#from xgboost import XGBClassifier
import sklearn
from sklearn.metrics import average_precision_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import cohen_kappa_score
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import NearestNeighbors


from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV

In [2]:
filename = 'events.csv'
events = pd.read_csv('./data/' + filename)
shots = events[(events.event_type==1)]

In [3]:
shots_prediction = shots.iloc[:,-6:]
dummies = pd.get_dummies(shots_prediction, columns=['location', 'bodypart','assist_method', 'situation'])
dummies.columns = ['is_goal', 'fast_break', 'loc_centre_box', 'loc_diff_angle_lr', 'diff_angle_left', 
                   'diff_angle_right', 'left_side_box', 'left_side_6ybox', 'right_side_box', 'right_side_6ybox', 
                   'close_range', 'penalty', 'outside_box', 'long_range', 'more_35y', 'more_40y', 'not_recorded', 
                   'right_foot', 'left_foot', 'header', 'no_assist', 'assist_pass', 'assist_cross', 'assist_header', 
                   'assist_through_ball', 'open_play', 'set_piece', 'corner', 'free_kick']
dummies.head()

,is_goal,fast_break,loc_centre_box,loc_diff_angle_lr,diff_angle_left,diff_angle_right,left_side_box,left_side_6ybox,right_side_box,right_side_6ybox,...,header,no_assist,assist_pass,assist_cross,assist_header,assist_through_ball,open_play,set_piece,corner,free_kick
0,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
13,1,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,1,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0

In [4]:
X = dummies.iloc[:,1:]
y = dummies.iloc[:,0]
print(X.shape)
print(y.shape)

(229135, 28)
(229135,)

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=1)

In [6]:
#mlp = MLPClassifier(random_state=0, hidden_layer_sizes=(28,28,28,28,20,10), 
#                    max_iter=2000, activation='relu' , learning_rate='adaptive')

pipeline = make_pipeline(MLPClassifier(hidden_layer_sizes=(28,28,28,28)))
hyperparameters = { 'mlpclassifier__activation' : ['relu', 'logistic'],
                  'mlpclassifier__learning_rate': ['adaptive', 'constant'],
                  'mlpclassifier__solver' : ['sgd' , 'adam']}
clf = RandomForestClassifier(n_estimators=500)
MLPClassifier().get_params().keys()

dict_keys(['activation', 'alpha', 'batch_size', 'beta_1', 'beta_2', 'early_stopping', 'epsilon', 'hidden_layer_sizes', 'learning_rate', 'learning_rate_init', 'max_fun', 'max_iter', 'momentum', 'n_iter_no_change', 'nesterovs_momentum', 'power_t', 'random_state', 'shuffle', 'solver', 'tol', 'validation_fraction', 'verbose', 'warm_start'])

In [7]:
#mlp.fit(X_train, y_train)
clf.fit(X_train, y_train)

GridSearchCV(cv=10, error_score=nan,
             estimator=Pipeline(memory=None,
                                steps=[('mlpclassifier',
                                        MLPClassifier(activation='relu',
                                                      alpha=0.0001,
                                                      batch_size='auto',
                                                      beta_1=0.9, beta_2=0.999,
                                                      early_stopping=False,
                                                      epsilon=1e-08,
                                                      hidden_layer_sizes=(28,
                                                                          28,
                                                                          28,
                                                                          28),
                                                      learning_rate='constant',
                                                      learning_rate_init=0.001,
                                                      max_fun=15000,
                                                      max_iter=200,
                                                      momentum=0.9,
                                                      n_iter_no_chang...
                                                      solver='adam', tol=0.0001,
                                                      validation_fraction=0.1,
                                                      verbose=False,
                                                      warm_start=False))],
                                verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'mlpclassifier__activation': ['relu', 'logistic'],
                         'mlpclassifier__learning_rate': ['adaptive',
                                                          'constant'],
                         'mlpclassifier__solver': ['sgd', 'adam']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [9]:
mlp = clf
mlp.score(X_train, y_train)
mlp.score(X_test, y_test)
accuracy = mlp.score(X_test, y_test)
print('The accuracy of classifying whether a shot is goal or not is {:.2f} %.'.format(accuracy*100))
y_pred = mlp.predict_proba(X_test)
predict = mlp.predict(X_test)
y_total = y_train.count()
y_positive = y_train.sum()
print('The training set contains {} examples of which {} are positives.'.format(y_total, y_positive))
auc_roc = roc_auc_score(y_test, y_pred[:,1])
print('Our MLP classifier obtains an AUC-ROC of {:.4f}.'.format(auc_roc))
auc_pr_baseline = y_positive / y_total
print('The baseline performance for AUC-PR is {:.4f}. This is what we would get by random guessing'.format(auc_pr_baseline))
auc_pr = average_precision_score(y_test, y_pred[:,1])
print('Our MLP classifier obtains an AUC-PR of {:.4f}.'.format(auc_pr))
cohen_kappa = cohen_kappa_score(y_test,predict)
print('Our classifier obtains a Cohen Kappa of {:.4f}.'.format(cohen_kappa))
MSE = sklearn.metrics.mean_squared_error(y_test, y_pred[:,1])
print('Our MLP classifier obtains a Mean Squared Error (MSE) of {:.4f}.'.format(MSE))

The accuracy of classifying whether a shot is goal or not is 91.10 %.
The training set contains 148937 examples of which 15937 are positives.
Our MLP classifier obtains an AUC-ROC of 0.8191.
The baseline performance for AUC-PR is 0.1070. This is what we would get by random guessing
Our MLP classifier obtains an AUC-PR of 0.4746.
Our classifier obtains a Cohen Kappa of 0.3525.
Our MLP classifier obtains a Mean Squared Error (MSE) of 0.0726.

In [10]:


print('Confusion Matrix:')
print(confusion_matrix(y_test,predict))
print('Report:')
print(classification_report(y_test,predict))

Confusion Matrix:
[[70782   912]
 [ 6223  2281]]
Report:
              precision    recall  f1-score   support

           0       0.92      0.99      0.95     71694
           1       0.71      0.27      0.39      8504

    accuracy                           0.91     80198
   macro avg       0.82      0.63      0.67     80198
weighted avg       0.90      0.91      0.89     80198

In [11]:
predictions = X_test.copy()
predictions['true_goals'] = y_test
predictions['expected_goals'] = y_pred[:,1]
predictions['difference'] = predictions['expected_goals'] - predictions['true_goals']
predictions = predictions.iloc[:,28:31]

In [12]:
ypred2 = mlp.predict_proba(X_train)
predictions_train = X_train.copy()
predictions_train['true_goals'] = y_train
predictions_train['expected_goals'] = ypred2[:,1]
predictions_train['difference'] = predictions_train['expected_goals'] - predictions_train['true_goals']
predictions_train = predictions_train.iloc[:,28:31]
all_predictions = pd.concat([predictions, predictions_train], axis=0)
events2 = pd.concat([events, all_predictions], axis=1)
shots2 = events2[events2.event_type==1]

In [13]:
xG_players = shots2[['player', 'event_type', 'true_goals', 'expected_goals', 'difference']].groupby('player').sum()
xG_players.columns = ['n_shots', 'goals_scored', 'expected_goals', 'difference']
xG_players[['goals_scored', 'expected_goals']].corr()

                goals_scored  expected_goals
goals_scored        1.000000        0.977358
expected_goals      0.977358        1.000000

In [14]:
xG_players.sort_values(['difference', 'goals_scored'])
#messi marcou mais golos do que o esperado, revelando-se o melhor neste parametro

                    n_shots  goals_scored  expected_goals  difference
player
lionel messi            914         205.0      139.962330  -65.037670
cristiano ronaldo      1190         198.0      158.362649  -39.637351
zlatan ibrahimovic      774         153.0      113.413243  -39.586757
gonzalo higuain         552         118.0       81.005710  -36.994290
luis suarez             433          96.0       60.446785  -35.553215
...                     ...           ...             ...         ...
adrian mutu             197          17.0       24.020137    7.020137
bostjan cesar            69           4.0       11.762915    7.762915
mats hummels            121          10.0       18.149264    8.149264
amauri                  225          20.0       29.929387    9.929387
jesus navas             274           9.0       21.134877   12.134877

[4787 rows x 4 columns]

In [15]:
xG_players.sort_values(['expected_goals'], ascending=False)
#Cristiano Ã© o jogador que deveria ter marcado mais golos segundo o modelo

                    n_shots  goals_scored  expected_goals  difference
player
cristiano ronaldo      1190         198.0      158.362649  -39.637351
lionel messi            914         205.0      139.962330  -65.037670
zlatan ibrahimovic      774         153.0      113.413243  -39.586757
edinson cavani          623         121.0      109.254861  -11.745139
robert lewandowski      633         124.0       91.490520  -32.509480
...                     ...           ...             ...         ...
kader                     1           0.0        0.008865    0.008865
moi                       1           0.0        0.007661    0.007661
hassane kamara            1           0.0        0.006394    0.006394
mattia aramu              1           0.0        0.000013    0.000013
pascal berenguer          1           0.0        0.000003    0.000003

[4787 rows x 4 columns]

In [16]:
headers = events2[(events2.event_type==1) & (events2.bodypart==3)]
headers_players = headers[['player', 'event_type', 'true_goals', 'expected_goals', 'difference']].groupby('player').sum()
headers_players.columns = ['n_headers', 'goals_scored', 'expected_goals', 'difference']
headers_players.sort_values(['difference'])
#Cristiano Ã© o melhor de cabeÃ§a marcou mais golos que o esperado

                          n_headers  goals_scored  expected_goals  difference
player
cristiano ronaldo               159          36.0       19.063432  -16.936568
mario mandzukic                 124          28.0       13.960981  -14.039019
fernando llorente               141          25.0       15.003382   -9.996618
sloan privat                     86          17.0        9.268654   -7.731346
pierreemerick aubameyang         59          14.0        7.150346   -6.849654
...                             ...           ...             ...         ...
bostjan cesar                    46           2.0        5.951973    3.951973
naldo                           112           7.0       11.587438    4.587438
raphael varane                   50           1.0        5.647221    4.647221
sokratis                         62           3.0        8.030329    5.030329
mats hummels                     80           5.0       10.458275    5.458275

[3354 rows x 4 columns]