In [1]:
import sys

import pandas as pd
import numpy as np
#import matplotlib as plt
#from matplotlib import pyplot
#import scipy as sp
#from xgboost import XGBClassifier
import sklearn
from sklearn.metrics import average_precision_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import cohen_kappa_score
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn import svm

from sklearn.metrics import mean_squared_error, r2_score

from sklearn import preprocessing

from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV

In [2]:
filename = 'ginf.csv'
games = pd.read_csv('./data/' + filename)
selected = games[games.odd_over.notnull() & games.odd_under.notnull()].copy()
selected

,id_odsp,link_odsp,adv_stats,date,league,season,country,ht,at,fthg,ftag,odd_h,odd_d,odd_a,odd_over,odd_under,odd_bts,odd_bts_n
9135,d4i30ksD/,/soccer/france/ligue-1/bastia-paris-sg-d4i30ksD/,True,2016-08-12,F1,2017,france,Bastia,Paris Saint-Germain,0,1,12.13,5.50,1.38,1.92,2.12,2.25,1.74
9136,OAqkOhZJ/,/soccer/france/ligue-1/monaco-guingamp-OAqkOhZJ/,True,2016-08-12,F1,2017,france,AS Monaco,Guingamp,2,2,1.77,3.85,6.20,2.14,1.83,2.05,1.93
9137,21rgNClQ/,/soccer/france/ligue-1/caen-lorient-21rgNClQ/,True,2016-08-13,F1,2017,france,Caen,Lorient,3,2,2.46,3.32,3.50,2.28,1.78,1.95,2.02
9138,4j0rLEUb/,/soccer/england/premier-league/southampton-wat...,True,2016-08-13,E0,2017,england,Southampton,Watford,1,1,1.84,3.85,5.10,2.15,1.84,2.05,1.93
9139,6Fbj3icf/,/soccer/france/ligue-1/montpellier-angers-6Fbj...,True,2016-08-13,F1,2017,france,Montpellier,Angers,1,0,1.95,3.36,5.50,2.80,1.53,2.40,1.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10107,xAkY8l6R/,/soccer/italy/serie-a/genoa-crotone-xAkY8l6R/,True,2017-01-22,I1,2017,italy,Genoa,Crotone,2,2,1.97,4.35,8.00,1.95,2.03,2.03,1.86
10108,xSU9scI9/,/soccer/england/premier-league/chelsea-hull-ci...,True,2017-01-22,E0,2017,england,Chelsea,Hull,2,0,1.19,8.50,20.00,1.54,2.68,2.40,1.66
10109,xY7uZwOI/,/soccer/france/ligue-1/monaco-lorient-xY7uZwOI/,True,2017-01-22,F1,2017,france,AS Monaco,Lorient,4,0,1.32,6.24,11.50,1.53,3.08,1.80,2.25
10110,YyeGxMX8/,/soccer/spain/laliga/betis-gijon-YyeGxMX8/,True,2017-01-22,SP1,2017,spain,Real Betis,Sporting Gijon,0,0,1.74,4.07,5.90,2.20,1.89,2.05,1.86
10111,z5L2OT5E/,/soccer/italy/serie-a/atalanta-sampdoria-z5L2O...,True,2017-01-22,I1,2017,italy,Atalanta,Sampdoria,1,0,1.79,3.96,5.40,1.90,2.07,1.80,2.16

In [3]:
selected['total'] = selected['fthg'] + selected['ftag']

col = 'total'
conditions = [selected[col] < 2.5 , selected[col] > 2.5]
choices = ['under','over']
selected['total'] = np.select(conditions,choices,default=np.nan)
selected

,id_odsp,link_odsp,adv_stats,date,league,season,country,ht,at,fthg,ftag,odd_h,odd_d,odd_a,odd_over,odd_under,odd_bts,odd_bts_n,total
9135,d4i30ksD/,/soccer/france/ligue-1/bastia-paris-sg-d4i30ksD/,True,2016-08-12,F1,2017,france,Bastia,Paris Saint-Germain,0,1,12.13,5.50,1.38,1.92,2.12,2.25,1.74,under
9136,OAqkOhZJ/,/soccer/france/ligue-1/monaco-guingamp-OAqkOhZJ/,True,2016-08-12,F1,2017,france,AS Monaco,Guingamp,2,2,1.77,3.85,6.20,2.14,1.83,2.05,1.93,over
9137,21rgNClQ/,/soccer/france/ligue-1/caen-lorient-21rgNClQ/,True,2016-08-13,F1,2017,france,Caen,Lorient,3,2,2.46,3.32,3.50,2.28,1.78,1.95,2.02,over
9138,4j0rLEUb/,/soccer/england/premier-league/southampton-wat...,True,2016-08-13,E0,2017,england,Southampton,Watford,1,1,1.84,3.85,5.10,2.15,1.84,2.05,1.93,under
9139,6Fbj3icf/,/soccer/france/ligue-1/montpellier-angers-6Fbj...,True,2016-08-13,F1,2017,france,Montpellier,Angers,1,0,1.95,3.36,5.50,2.80,1.53,2.40,1.70,under
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10107,xAkY8l6R/,/soccer/italy/serie-a/genoa-crotone-xAkY8l6R/,True,2017-01-22,I1,2017,italy,Genoa,Crotone,2,2,1.97,4.35,8.00,1.95,2.03,2.03,1.86,over
10108,xSU9scI9/,/soccer/england/premier-league/chelsea-hull-ci...,True,2017-01-22,E0,2017,england,Chelsea,Hull,2,0,1.19,8.50,20.00,1.54,2.68,2.40,1.66,under
10109,xY7uZwOI/,/soccer/france/ligue-1/monaco-lorient-xY7uZwOI/,True,2017-01-22,F1,2017,france,AS Monaco,Lorient,4,0,1.32,6.24,11.50,1.53,3.08,1.80,2.25,over
10110,YyeGxMX8/,/soccer/spain/laliga/betis-gijon-YyeGxMX8/,True,2017-01-22,SP1,2017,spain,Real Betis,Sporting Gijon,0,0,1.74,4.07,5.90,2.20,1.89,2.05,1.86,under
10111,z5L2OT5E/,/soccer/italy/serie-a/atalanta-sampdoria-z5L2O...,True,2017-01-22,I1,2017,italy,Atalanta,Sampdoria,1,0,1.79,3.96,5.40,1.90,2.07,1.80,2.16,under

In [42]:
temp = selected.iloc[:,[-1,5,7,8,15]]
dummies = pd.get_dummies(temp, columns=['ht', 'at','season'])
dummies

,total,odd_under,ht_AC Milan,ht_AS Monaco,ht_AS Nancy Lorraine,ht_AS Roma,ht_Alaves,ht_Angers,ht_Arsenal,ht_Atalanta,...,at_US Pescara,at_Udinese,at_Valencia,at_VfL Wolfsburg,at_Villarreal,at_Watford,at_Werder Bremen,at_West Brom,at_West Ham,season_2017
9135,under,2.12,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9136,over,1.83,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9137,over,1.78,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
9138,under,1.84,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
9139,under,1.53,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10107,over,2.03,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10108,under,2.68,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10109,over,3.08,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10110,under,1.89,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
10111,under,2.07,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [43]:
data = dummies
X = data.iloc[:,1:]
y = data.iloc[:,:1]
#y = np.ravel(y)
print(X.shape)
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=1)
y

(977, 198)
(977, 1)

       total
9135   under
9136    over
9137    over
9138   under
9139   under
...      ...
10107   over
10108  under
10109   over
10110  under
10111  under

[977 rows x 1 columns]

In [85]:
pipeline = make_pipeline(KNeighborsClassifier())

hyperparameters = { 'kneighborsclassifier__n_neighbors' : [15, 40, 100],
                  'kneighborsclassifier__algorithm': ['auto', 'ball_tree', 'kd_tree'],
                  'kneighborsclassifier__weights': ['uniform','distance']}


clf = GridSearchCV(pipeline, hyperparameters, cv=10)

In [104]:
#clf = RandomForestClassifier(n_estimators=200)
#clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(30,20,3), random_state=1 , max_iter = 1000)
clf = KNeighborsClassifier(n_neighbors=105, algorithm='auto',weights='uniform');
#clf = RandomForestClassifier(n_estimators=400)
#clf = svm.SVC(kernel='linear')
clf.fit(X_train,y_train)

<ipython-input-104-ccdd06010d74>:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=105, p=2,
                     weights='uniform')

In [105]:
accuracy = clf.score(X_test, y_test)
#y_pred = clf.predict_proba(X_test)
#predict = clf.predict(X_test)
#y_total = y_train.count()
#y_positive = y_train.sum()
#print('The training set contains {} examples (games) of which {} are positives .'.format(y_total, y_positive))
print('The accuracy of classifying is {:.2f} %'.format(accuracy*100))

The accuracy of classifying is 59.06 %