In [1]:
import sys

import pandas as pd
import numpy as np
#import matplotlib as plt
#from matplotlib import pyplot
#import scipy as sp
#from xgboost import XGBClassifier
import sklearn
from sklearn.metrics import average_precision_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.metrics import cohen_kappa_score
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import mean_squared_error, r2_score

from sklearn import preprocessing

from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV


import joblib

In [4]:
filename = 'events.csv'
events = pd.read_csv('./data/' + filename)
subs = events[(events.event_type==7)]
subs.head()

,id_odsp,id_event,sort_order,time,text,event_type,event_type2,side,event_team,opponent,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
41,UFot0hit/,UFot0hit42,42,42,"Substitution, Hamburg. Anis Ben-Hatira replace...",7,NaN,2,Hamburg SV,Borussia Dortmund,...,anis benhatira,jose paolo guerrero,NaN,NaN,0,NaN,NaN,0,NaN,0
46,UFot0hit/,UFot0hit47,47,47,"Substitution, Hamburg. Marcell Jansen replaces...",7,NaN,2,Hamburg SV,Borussia Dortmund,...,marcell jansen,eljero elia,NaN,NaN,0,NaN,NaN,0,NaN,0
83,UFot0hit/,UFot0hit84,84,73,"Substitution, Hamburg. Robert Tesche replaces ...",7,NaN,2,Hamburg SV,Borussia Dortmund,...,robert tesche,gojko kacar,NaN,NaN,0,NaN,NaN,0,NaN,0
88,UFot0hit/,UFot0hit89,89,76,"Substitution, Borussia Dortmund. Ivan Perisic ...",7,NaN,1,Borussia Dortmund,Hamburg SV,...,ivan perisic,chris lowe,NaN,NaN,0,NaN,NaN,0,NaN,0
89,UFot0hit/,UFot0hit90,90,78,"Substitution, Borussia Dortmund. Jakub Blaszcz...",7,NaN,1,Borussia Dortmund,Hamburg SV,...,jakub blaszczykowski,mario gotze,NaN,NaN,0,NaN,NaN,0,NaN,0

In [5]:
subs_prediction = subs.iloc[:, np.r_[3:6, 7:10, 12:14]]

#dummies = pd.get_dummies(subs_prediction, columns=['event_team','player_in','player_out'])
#dummies.head()
subs_prediction.head()

,time,text,event_type,side,event_team,opponent,player_in,player_out
41,42,"Substitution, Hamburg. Anis Ben-Hatira replace...",7,2,Hamburg SV,Borussia Dortmund,anis benhatira,jose paolo guerrero
46,47,"Substitution, Hamburg. Marcell Jansen replaces...",7,2,Hamburg SV,Borussia Dortmund,marcell jansen,eljero elia
83,73,"Substitution, Hamburg. Robert Tesche replaces ...",7,2,Hamburg SV,Borussia Dortmund,robert tesche,gojko kacar
88,76,"Substitution, Borussia Dortmund. Ivan Perisic ...",7,1,Borussia Dortmund,Hamburg SV,ivan perisic,chris lowe
89,78,"Substitution, Borussia Dortmund. Jakub Blaszcz...",7,1,Borussia Dortmund,Hamburg SV,jakub blaszczykowski,mario gotze